name 'juliengk-stdlibplus'
version '0.1.1'
source 'git://github.com/juliengk/puppet-stdlibplus.git'
author 'juliengk'
license 'Apache License, Version 2.0'
summary 'Puppet Standard Library Plus module'
description 'Puppet Standard Library Plus module'
project_page 'https://github.com/juliengk/puppet-stdlibplus'
